# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  WAGO_PAYLOAD: "{}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build Payload
        run: |
            cat ${{ github.workspace }}/milk.wa >> $WAGO_PAYLOAD

      # Runs a set of commands using the runners shell
      - name: Web Request Action
  # You may pin to the exact commit or the version.
  # uses: Satak/webrequest-action@5fafb47657920704ad01cfb820fd9aacd81d74cf
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: https://addons.wago.io/api/projects/H1KXkXxhU/version
          # Web request method (`GET`, `POST`, `PUT`, `PATCH`, `DELETE`)
          method: POST
          # Web request payload in JSON format
          payload: ${{ WAGO_PAYLOAD }}
          # Web request headers in JSON format
          #headers: # optional
          # username for BASIC auth
          #username: # optional
          # password for BASIC auth
          password: ${{ secrets.GITHUB_TOKEN }}
